version: "3.9"
services:
  rushlesserver:
    image: rushlesserver:latest
    container_name: rushlesserver
    volumes:
      # Bind mount .env dari backend
      - ./backend/.env:/app/backend/.env

      # Uploads tetap di volume
      - rushlesserver_uploads:/app/backend/public/uploads

      # Data MariaDB disimpan di volume
      - rushlesserver_db:/var/lib/mysql

      # Apache config di-host supaya container baru pakai config terbaru
      - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./apache/ports.conf:/etc/apache2/ports.conf

    ports:
      - "${WEB_PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
    restart: always

volumes:
  rushlesserver_uploads:
  rushlesserver_db:
